# Generated by Django 3.0 on 2023-03-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snme', models.CharField(max_length=120)),
                ('sage', models.IntegerField()),
                ('semail', models.CharField(max_length=120)),
            ],
        ),
    ]
